sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ragpark/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ragpark/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-533483506083'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY